import 'dart:io';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../domain/repositories/products_repository.dart';
import 'add_product_event.dart';
import 'add_product_state.dart';
import '../../../home/domain/entities/home_entities.dart';

class AddProductBloc extends Bloc<AddProductEvent, AddProductState> {
  final ProductsRepository _productsRepository;
  File? _selectedImage;

  AddProductBloc({required ProductsRepository productsRepository})
      : _productsRepository = productsRepository,
        super(AddProductInitial()) {
    on<AddProductImagePicked>(_onImagePicked);
    on<AddProductSubmitted>(_onSubmitted);
  }

  void _onImagePicked(AddProductImagePicked event, Emitter<AddProductState> emit) {
    _selectedImage = File(event.image.path);
    emit(AddProductImageSelected(_selectedImage!));
  }

  Future<void> _onSubmitted(AddProductSubmitted event, Emitter<AddProductState> emit) async {
    emit(AddProductLoading());
    try {
      final product = Product(
        id: '', // Generated by backend
        name: event.name,
        location: event.location,
        imageUrl: '', // Will be set by repository after upload
        price: event.price,
        description: event.description,
        isFeatured: event.isFeatured,
        ownerId: event.ownerId,
        category: event.category,
      );

      final result = await _productsRepository.addProduct(product, _selectedImage);

      result.fold(
        (failure) => emit(AddProductFailure(failure.message)),
        (_) {
            _selectedImage = null; // Reset image after success
            emit(AddProductSuccess());
        },
      );
    } catch (e) {
      emit(AddProductFailure(e.toString()));
    }
  }
}
