// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBz9W__2uoMbiRshIAEOq12TgM7A8RfpQ',
    appId: '1:713792125410:android:460aef28f6723a752ba1bb',
    messagingSenderId: '713792125410',
    projectId: 'flxmarket',
    storageBucket: 'flxmarket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_6YW8Wb_mCs-OJw7fUCWrqMuNUyJ1TQ',
    appId: '1:713792125410:ios:7dde858f60a298bb2ba1bb',
    messagingSenderId: '713792125410',
    projectId: 'flxmarket',
    storageBucket: 'flxmarket.firebasestorage.app',
    iosBundleId: 'com.example.flxMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9QzjWOPQ4CTqu7TA-FAU_u9jQC9HzcPc',
    appId: '1:295411715838:web:b9cf7ea61fc74daac79faf',
    messagingSenderId: '295411715838',
    projectId: 'service-reservation-system',
    authDomain: 'service-reservation-system.firebaseapp.com',
    storageBucket: 'service-reservation-system.firebasestorage.app',
    measurementId: 'G-J7PCKF42KV',
  );
}